// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from 'path';
import dotenv from 'dotenv';

dotenv.config();
if (!process.env['DATABASE_URL']) {
  dotenv.config({ path: path.resolve(__dirname, '../.env') });
}
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL']!,
  },
  // PgBouncer configuration for connection pooling
  // Only used when PGBOUNCER_URL is set (local development or external pooler)
  // Neon already has a built-in pooler via the connection string
  datasources: {
    db: {
      url: process.env['PGBOUNCER_URL'] || process.env['DATABASE_URL']!,
    },
  },
});
